"""Structured-output matchers with coercion from literals and predicates."""

from __future__ import annotations

from agent_spec_kit.match.api import (
    BaseMatcher,
    ForbidRule,
    ListExactMatcher,
    ListOfMatcher,
    ListUnorderedMatcher,
    MatchError,
    MatchResult,
    ObjectMatcher,
    Path,
    PredicateMatcher,
    RegexMatcher,
    RequireRule,
    Rule,
    TransformMatcher,
    any_value,
    check,
    field,
    forbid,
    list_exact,
    list_of,
    list_unordered,
    match,
    number,
    object,
    one_of,
    optional,
    regex,
    require,
    string,
    transform,
)

__all__ = [
    "BaseMatcher",
    "ForbidRule",
    "ListExactMatcher",
    "ListOfMatcher",
    "ListUnorderedMatcher",
    "MatchError",
    "MatchResult",
    "ObjectMatcher",
    "Path",
    "PredicateMatcher",
    "RegexMatcher",
    "RequireRule",
    "Rule",
    "TransformMatcher",
    "any_value",
    "check",
    "field",
    "forbid",
    "list_exact",
    "list_of",
    "list_unordered",
    "match",
    "number",
    "object",
    "one_of",
    "optional",
    "regex",
    "require",
    "string",
    "transform",
]
