"""Structured-output matchers with coercion from literals and predicates.

Import as ``import agent_spec_kit.match as m``, build specs with :func:`m.object`,
:func:`m.list`, literals, and helpers (:func:`m.string`, :func:`m.optional`, …), then
validate with :func:`m.check`.
"""

from __future__ import annotations

from agent_spec_kit.match.api import (
    BaseMatcher,
    ForbidRule,
    ListMatcher,
    ListOfMatcher,
    MatchError,
    MatchResult,
    ObjectMatcher,
    Path,
    PredicateMatcher,
    RegexMatcher,
    RequireRule,
    Rule,
    TransformMatcher,
    any_value,
    check,
    field,
    forbid,
    list,
    list_of,
    match,
    number,
    object,
    one_of,
    optional,
    regex,
    require,
    string,
    transform,
)

__all__ = [
    "BaseMatcher",
    "ForbidRule",
    "ListMatcher",
    "ListOfMatcher",
    "MatchError",
    "MatchResult",
    "ObjectMatcher",
    "Path",
    "PredicateMatcher",
    "RegexMatcher",
    "RequireRule",
    "Rule",
    "TransformMatcher",
    "any_value",
    "check",
    "field",
    "forbid",
    "list",
    "list_of",
    "match",
    "number",
    "object",
    "one_of",
    "optional",
    "regex",
    "require",
    "string",
    "transform",
]
